version: '3.8'

services:
  app:    
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - .:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "/workspace/buildAndRun.sh"
    network_mode: service:db
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd1234
      POSTGRES_DB: doodle
    ports:
      - 5432:5432
      - 8080:8080 # for app
    volumes:
      - pg_db:/var/lib/postgresql/data
      - ./dbconfig/:/docker-entrypoint-initdb.d/

volumes:
  pg_db: